[2024-01-14T22:07:52.255+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: online_retail.test_staging manual__2024-01-14T22:05:03.301783+00:00 [queued]>
[2024-01-14T22:07:52.290+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: online_retail.test_staging manual__2024-01-14T22:05:03.301783+00:00 [queued]>
[2024-01-14T22:07:52.291+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-14T22:07:52.326+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): test_staging> on 2024-01-14 22:05:03.301783+00:00
[2024-01-14T22:07:52.349+0000] {standard_task_runner.py:57} INFO - Started process 350 to run task
[2024-01-14T22:07:52.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'online_retail', 'test_staging', 'manual__2024-01-14T22:05:03.301783+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp1q_i06nr']
[2024-01-14T22:07:52.357+0000] {standard_task_runner.py:85} INFO - Job 85: Subtask test_staging
[2024-01-14T22:07:52.476+0000] {task_command.py:416} INFO - Running <TaskInstance: online_retail.test_staging manual__2024-01-14T22:05:03.301783+00:00 [running]> on host 6808d18c086e
[2024-01-14T22:07:52.663+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='online_retail' AIRFLOW_CTX_TASK_ID='test_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-01-14T22:05:03.301783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-14T22:05:03.301783+00:00'
[2024-01-14T22:07:52.672+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-14T22:07:52.673+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt test --project-dir /opt/***/dags/dbts/project-dbt --profiles-dir /opt/***/dags/dbts/project-dbt -select stg_online_retail stg_country']
[2024-01-14T22:07:52.700+0000] {subprocess.py:86} INFO - Output:
[2024-01-14T22:08:02.592+0000] {subprocess.py:93} INFO - [0m22:08:02  Running with dbt=1.7.4
[2024-01-14T22:08:02.599+0000] {subprocess.py:93} INFO - [0m22:08:02  Encountered an error:
[2024-01-14T22:08:02.599+0000] {subprocess.py:93} INFO - Runtime Error
[2024-01-14T22:08:02.600+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /opt/***/dags/dbts/project-dbt/dbt_project.yml
[2024-01-14T22:08:02.600+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2024-01-14T22:08:02.601+0000] {subprocess.py:93} INFO - 
[2024-01-14T22:08:04.015+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-01-14T22:08:04.058+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-01-14T22:08:04.069+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=online_retail, task_id=test_staging, execution_date=20240114T220503, start_date=20240114T220752, end_date=20240114T220804
[2024-01-14T22:08:04.110+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 85 for task test_staging (Bash command failed. The command returned a non-zero exit code 2.; 350)
[2024-01-14T22:08:04.158+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-14T22:08:04.188+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
